repos:
  - repo: local
    hooks:
      - id: ban-yml
        name: ban .yml file extension
        entry: scripts/ban_some_extensions.sh
        language: unsupported_script
        files: \.ya?ml$
      - id: dprint-check
        name: check format with dprint
        entry: dprint check
        language: unsupported
        files: \.(json|jsonc|md|yaml)$
      - id: shellcheck
        name: run ShellCheck
        language: unsupported
        entry: shellcheck
        files: \.sh$
      - id: actionlint
        name: run actionlint
        language: unsupported
        entry: actionlint
        files: ^\.github/workflows/.+\.yaml$
