name: Checks

on:
  push:
    branches: [main, init-dev]
  pull_request:
    branches: [main]
  schedule:
    - cron: "45 16 */3 * *"
  workflow_dispatch:
permissions:
  contents: read
defaults:
  run:
    shell: bash --noprofile --norc -euxo pipefail {0}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dprint/check@9cb3a2b17a8e606d37aae341e49df3654933fc23 # v2.3
      - name: shellcheck
        run: |
          # Word splitting just causes a workflow failure.
          # shellcheck disable=2046
          shellcheck $(git ls-files '*.sh')

  test-fish-latest:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-latest
          - ubuntu-slim
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check if fish tools are not installed yet
        run: |
          if command -v fish           ; then exit 1; fi
          if command -v fish_indent    ; then exit 2; fi
          if command -v fish_key_reader; then exit 3; fi
      - name: Run the action without input
        uses: ./
      - name: Check if fish tools are installed
        run: |
          if ! fish --version           ; then exit 1; fi
          if ! fish_indent --version    ; then exit 2; fi
          if ! fish_key_reader --version; then exit 3; fi

  test-fish-versions:
    strategy:
      matrix:
        version:
          - "4.1.2"
          - "4.6.0"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check if fish tools are not installed yet
        run: |
          if command -v fish; then exit 1; fi
          if command -v fish_indent; then exit 2; fi
          if command -v fish_key_reader; then exit 3; fi
      - name: Run the action with input
        uses: ./
        with:
          fish-version: ${{ matrix.version }}
      - name: Check if the versions of fish tools are correct
        env:
          TEST_VERSION: ${{ matrix.version }}
        run: |
          if ! [[ "$(fish --version)" =~ " $TEST_VERSION"$ ]]           ; then exit 1; fi
          if ! [[ "$(fish_indent --version)" =~ " $TEST_VERSION"$ ]]    ; then exit 2; fi
          if ! [[ "$(fish_key_reader --version)" =~ " $TEST_VERSION"$ ]]; then exit 3; fi
